//
// Autogenerated by Thrift Compiler (0.14.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');

var SecondaryQrCodeLoginService_ttypes = require('./SecondaryQrCodeLoginService_types');


var ttypes = require('./SecondaryQrCodeLoginPermitNoticeService_types');
//HELPER FUNCTIONS AND STRUCTURES

var SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.CheckQrCodeVerifiedRequest(args.request);
    }
  }
};
SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_args.prototype = {};
SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.CheckQrCodeVerifiedRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_args.prototype.write = function(output) {
  output.writeStructBegin('SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result = function(args) {
  this.success = null;
  this.e = null;
  if (args instanceof SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.CheckQrCodeVerifiedResponse(args.success);
    }
    if (args.e !== undefined && args.e !== null) {
      this.e = args.e;
    }
  }
};
SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result.prototype = {};
SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.CheckQrCodeVerifiedResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result.prototype.write = function(output) {
  output.writeStructBegin('SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.CheckPinCodeVerifiedRequest(args.request);
    }
  }
};
SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_args.prototype = {};
SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.CheckPinCodeVerifiedRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_args.prototype.write = function(output) {
  output.writeStructBegin('SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result = function(args) {
  this.success = null;
  this.e = null;
  if (args instanceof SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.CheckPinCodeVerifiedResponse(args.success);
    }
    if (args.e !== undefined && args.e !== null) {
      this.e = args.e;
    }
  }
};
SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result.prototype = {};
SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.CheckPinCodeVerifiedResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result.prototype.write = function(output) {
  output.writeStructBegin('SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SecondaryQrCodeLoginPermitNoticeServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
SecondaryQrCodeLoginPermitNoticeServiceClient.prototype = {};
SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.seqid = function() { return this._seqid; };
SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.checkQrCodeVerified = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_checkQrCodeVerified(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_checkQrCodeVerified(request);
  }
};

SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.send_checkQrCodeVerified = function(request) {
  var output = new this.pClass(this.output);
  var params = {
    request: request
  };
  var args = new SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_args(params);
  try {
    output.writeMessageBegin('checkQrCodeVerified', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.recv_checkQrCodeVerified = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('checkQrCodeVerified failed: unknown result');
};

SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.checkPinCodeVerified = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_checkPinCodeVerified(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_checkPinCodeVerified(request);
  }
};

SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.send_checkPinCodeVerified = function(request) {
  var output = new this.pClass(this.output);
  var params = {
    request: request
  };
  var args = new SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_args(params);
  try {
    output.writeMessageBegin('checkPinCodeVerified', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

SecondaryQrCodeLoginPermitNoticeServiceClient.prototype.recv_checkPinCodeVerified = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('checkPinCodeVerified failed: unknown result');
};
var SecondaryQrCodeLoginPermitNoticeServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
SecondaryQrCodeLoginPermitNoticeServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
SecondaryQrCodeLoginPermitNoticeServiceProcessor.prototype.process_checkQrCodeVerified = function(seqid, input, output) {
  var args = new SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.checkQrCodeVerified.length === 1) {
    Q.fcall(this._handler.checkQrCodeVerified.bind(this._handler),
      args.request
    ).then(function(result) {
      var result_obj = new SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result({success: result});
      output.writeMessageBegin("checkQrCodeVerified", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException) {
        result = new SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result(err);
        output.writeMessageBegin("checkQrCodeVerified", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("checkQrCodeVerified", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.checkQrCodeVerified(args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException) {
        result_obj = new SecondaryQrCodeLoginPermitNoticeService_checkQrCodeVerified_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("checkQrCodeVerified", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("checkQrCodeVerified", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
SecondaryQrCodeLoginPermitNoticeServiceProcessor.prototype.process_checkPinCodeVerified = function(seqid, input, output) {
  var args = new SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.checkPinCodeVerified.length === 1) {
    Q.fcall(this._handler.checkPinCodeVerified.bind(this._handler),
      args.request
    ).then(function(result) {
      var result_obj = new SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result({success: result});
      output.writeMessageBegin("checkPinCodeVerified", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException) {
        result = new SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result(err);
        output.writeMessageBegin("checkPinCodeVerified", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("checkPinCodeVerified", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.checkPinCodeVerified(args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof SecondaryQrCodeLoginService_ttypes.SecondaryQrCodeException) {
        result_obj = new SecondaryQrCodeLoginPermitNoticeService_checkPinCodeVerified_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("checkPinCodeVerified", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("checkPinCodeVerified", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
